# Generated by Django 6.0.1 on 2026-03-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_checkout_request_id_payment_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('PROCESSING_FEE', 'Processing Fee'), ('DISBURSEMENT', 'Loan Disbursement'), ('REPAYMENT', 'Loan Repayment')], max_length=20),
        ),
    ]
