# Generated by Django 6.0.1 on 2026-02-01 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='admin_response',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='ai_response',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='image',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='message',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('AI', 'AI Responded'), ('ADMIN', 'Admin Responded'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('USER', 'User'), ('AI', 'AI'), ('ADMIN', 'Admin')], max_length=10)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='support/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='helpdesk.supportticket')),
            ],
        ),
    ]
