# Generated by Django 6.0.1 on 2026-03-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_remove_supportticket_admin_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='rating_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
