# Generated by Django 6.0.1 on 2026-03-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_address_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('Employed', 'Employed'), ('Self-employed', 'Self-employed'), ('Unemployed', 'Unemployed'), ('Student', 'Student')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
