# Generated by Django 6.0.1 on 2026-02-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='loan',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('WITHDRAW', 'Withdraw'), ('TOPUP', 'Top Up')], max_length=20),
        ),
    ]
