# Generated by Django 6.0.1 on 2026-02-11 08:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_loanapplication_fully_repaid'),
        ('wallet', '0005_alter_wallettransaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loanapplication'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('WITHDRAW', 'Withdraw'), ('TOPUP', 'Top Up'), ('REPAYMENT', 'Loan Repayment')], max_length=20),
        ),
    ]
