# Generated by Django 6.0.1 on 2026-02-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_remove_wallettransaction_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
