# Generated by Django 6.0.1 on 2026-02-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
