# Generated by Django 6.0.1 on 2026-02-18 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0023_alter_loanapplication_id_document_back_and_more'),
        ('wallet', '0009_wallet_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Liquidity Pool', max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('minimum_reserve', models.DecimalField(decimal_places=2, default=50000, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DISBURSEMENT', 'Loan Disbursement'), ('REPAYMENT', 'Loan Repayment'), ('TOPUP', 'Admin Topup'), ('WITHDRAWAL', 'Admin Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loanapplication')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('system_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.systemwallet')),
            ],
        ),
    ]
