# Generated by Django 6.0.1 on 2026-02-19 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_systemwallet_systemtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='status',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DISBURSEMENT', 'Loan Disbursed'), ('REPAYMENT', 'Loan Repayment'), ('WITHDRAWAL', 'User Withdrawal'), ('DEPOSIT', 'User Deposit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet'),
        ),
    ]
