# Generated by Django 6.0.1 on 2026-01-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='fraud_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='fraud_score',
            field=models.FloatField(default=0.0),
        ),
    ]
