# Generated by Django 6.0.1 on 2026-01-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplication_fraud_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='documents_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='id_document',
            field=models.FileField(default=None, upload_to='ids/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='id_number',
            field=models.CharField(default='41292983', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='reason_for_loan',
            field=models.TextField(default='business expansion'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Funded', 'Funded')], default='Pending', max_length=20),
        ),
    ]
