# Generated by Django 6.0.1 on 2026-01-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanapplication_documents_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='ids/'),
        ),
    ]
