# Generated by Django 6.0.1 on 2026-01-31 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loanapplication_id_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='funded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='id_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='reason_for_loan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.loanamount'),
        ),
    ]
