# Generated by Django 6.0.1 on 2026-01-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loanamount_loanapplication_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='predicted_probability',
            field=models.FloatField(default=0.0),
        ),
    ]
