# Generated by Django 6.0.1 on 2026-01-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loanapplication_predicted_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
