# Generated by Django 6.0.1 on 2026-01-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_loanapplication_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='id_document',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='id_document_back',
            field=models.FileField(blank=True, null=True, upload_to='ids/back/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='id_document_front',
            field=models.FileField(blank=True, null=True, upload_to='ids/front/'),
        ),
    ]
