# Generated by Django 6.0.1 on 2026-02-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_remove_loanapplication_id_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='disbursed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='processing_fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
