# Generated by Django 6.0.1 on 2026-02-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_loanapplication_disbursed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
