# Generated by Django 6.0.1 on 2026-02-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_alter_loanapplication_processing_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='processing_fee',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
