# Generated by Django 6.0.1 on 2026-02-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_alter_loanapplication_processing_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='id_document_back',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='ids/back/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='id_document_front',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='ids/front/'),
        ),
    ]
