# Generated by Django 6.0.1 on 2026-02-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_alter_loanapplication_id_document_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='amount_remaining',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
