# Generated by Django 6.0.1 on 2026-02-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_loanapplication_amount_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='fully_repaid',
            field=models.BooleanField(default=False),
        ),
    ]
