# Generated by Django 6.0.1 on 2026-02-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_loanapplication_fully_repaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='amount_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
