# Generated by Django 6.0.1 on 2026-02-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_loanapplication_interest_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='loan_amount',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='qualified_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
