# Generated by Django 6.0.1 on 2026-02-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0018_remove_loanapplication_loan_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='funded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
