# Generated by Django 6.0.1 on 2026-02-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0019_loanapplication_funded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='risk_reasons',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
