# Generated by Django 6.0.1 on 2026-02-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0020_loanapplication_risk_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='ast_default_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='on_time_repayment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='previous_loan_count',
            field=models.IntegerField(default=0),
        ),
    ]
