# Generated by Django 6.0.1 on 2026-02-15 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0021_loanapplication_ast_default_flag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='ast_default_flag',
            new_name='last_default_flag',
        ),
    ]
