# Generated by Django 6.0.1 on 2026-02-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0022_rename_ast_default_flag_loanapplication_last_default_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='id_document_back',
            field=models.FileField(blank=True, null=True, upload_to='ids/back/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='id_document_front',
            field=models.FileField(blank=True, null=True, upload_to='ids/front/'),
        ),
    ]
