# Generated by Django 6.0.1 on 2026-02-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0024_repaymentschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repaymentschedule',
            name='reminder_sent',
        ),
    ]
