# Generated by Django 6.0.1 on 2026-02-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0025_remove_repaymentschedule_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='repaymentschedule',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
