# Generated by Django 6.0.1 on 2026-03-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0028_loanreviewmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='id_authentic',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='id_authenticity_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='id_authenticity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Info Required', 'Info Required'), ('Funded', 'Funded')], default='Pending', max_length=20),
        ),
    ]
