# Generated by Django 6.0.1 on 2026-03-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0029_loanapplication_id_authentic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='ai_explanation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='kyc_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='kyc_face_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='risk_level',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
