# Generated by Django 6.0.1 on 2026-03-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0030_loanapplication_ai_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='kyc_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/selfies/'),
        ),
    ]
