# Generated by Django 6.0.1 on 2026-03-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0031_loanapplication_kyc_selfie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Pending KYC', 'Pending KYC'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Info Required', 'Info Required'), ('Funded', 'Funded')], default='Pending', max_length=20),
        ),
    ]
