# Generated by Django 6.0.1 on 2026-03-22 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0033_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loans_enabled', models.BooleanField(default=True)),
                ('min_loan_amount', models.IntegerField(default=1000)),
                ('max_loan_amount_new', models.IntegerField(default=10000)),
                ('max_loan_amount_bronze', models.IntegerField(default=30000)),
                ('max_loan_amount_silver', models.IntegerField(default=75000)),
                ('max_loan_amount_gold', models.IntegerField(default=150000)),
                ('max_loan_amount_platinum', models.IntegerField(default=500000)),
                ('min_interest_rate', models.FloatField(default=10.0)),
                ('max_interest_rate', models.FloatField(default=25.0)),
                ('maintenance_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
            },
        ),
    ]
