# Generated by Django 6.0.1 on 2026-04-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0034_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='ela_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='mrz_valid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
